config/routes.rb
ISIMarket::Application.routes.draw do
  
  root :to => 'homepage#index'
  get '/clientes/comprar'
  get '/clientes/cancelar'
  post '/clientes/entrar'
  match '/logout' => 'clientes#logout'
  match '/login' => 'clientes#login'
  resources :productos
  resources :recetas
  resources :clientes
  resources :homepage, :only => [:index]
  

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
   attr_accessible :nif, :nombre, :password, :n_cuenta, :direccion
   validates_uniqueness_of :nif
end

app/models/compra.rb
class Compra < ActiveRecord::Base
   attr_accessible :coste, :fecha
   # n_factura es id(clave surrogada)
   # validates_uniqueness_of :n_factura
end

app/models/efectuar_compra.rb
class Efectuar_compra < ActiveRecord::Base
  belongs_to :clientes
  belongs_to :productos
  belongs_to :compras
  validates_presence_of :clientes
  validates_presence_of :productos
  validates_presence_of :compras

end

app/models/producto.rb
class Producto < ActiveRecord::Base
   has_many :recetas
   attr_accessible :categoria, :nombre, :precio_venta, :precio_compra, :stock, :descripcion, :recetas
   # id(natural) es id(clave surrogada)
   # validates_uniqueness_of :id
   def self.all_categorias
    %w(verdura carne legumbre lacteo bebida otro)
  end
  
end

app/models/receta.rb
class Receta < ActiveRecord::Base
   has_many :productos
   attr_accessible :titulo, :preparacion, :puntuacion, :productos
   # id(natural) es id(clave surrogada)
   # validates_uniqueness_of :id
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def show
  @compra = session[:compra]
  @cliente = Cliente.find(params[:id])
  end
  def index
  end
  def new
  end
  def create
	@cliente = Cliente.create!(params[:clientes])
	session[:cliente]= @cliente
	total = 0
	productos = []
	session[:compra]= [total,productos] 
	flash[:notice]="El usuario #{session[:nombre]} fue registrado con exito."
	redirect_to productos_path
  end
  def edit
    @cliente = Cliente.find(params[:id])
  end
  def update
    @cliente = Cliente.find_by_id(params[:id])
    @cliente.update_attributes!(params[:cliente])
    flash[:notice] = "Datos actualizados"
    redirect_to producto_path(@producto)
  end
  def destroy
  end
  def comprar
    flash[:notice]="compra realizada con exito, total = #{session[:compra][0]}"
    total = 0
	productos = []
	session[:compra]= [total,productos]
	redirect_to cliente_path(session[:cliente])
  end
  def cancelar
    flash[:notice]="compra cancelada"
    total = 0
	productos = []
	session[:compra]= [total,productos]
	redirect_to cliente_path(session[:cliente])
  end
  
  def login
  end
  
  def entrar
    @cliente= Cliente.find_by_nif(params[:cliente][:nif])
    if @cliente  then
      if @cliente.password == params[:cliente][:pass] then
        session[:cliente]= @cliente
	    total = 0
	    productos = []
	    session[:compra]= [total,productos]
	    redirect_to productos_path
	  end
	else 
	  flash[:warning]="fallo de autenticacion"
	  redirect_to login_path
	end
  end
  
  def logout
    session[:cliente]= nil
    total = 0
	productos = []
	session[:compra]= [total,productos]
	flash[:notice]="sesion cerrada"
	redirect_to homepage_index_path
  end
  
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    #render :layout => false
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def show
    @producto = Producto.find_by_id(params[:id])
    @receta=Receta.all
    if not @producto then
      flash[:warning]= 'Producto no encontrado'
      redirect_to productos_path
    end
	render :partial => 'producto', :object => @producto and return if request.xhr?
  end
  def index
    @all_categorias = Producto.all_categorias
    @selected_categorias = params[:categorias] || {}
    if @selected_categorias == {}
      @selected_categorias = Hash[@all_categorias.map {|categoria| [categoria, categoria]}]
    end
    @productos = Producto.find_all_by_categoria(@selected_categorias.keys)
    
    if params[:comprado] then
      if session[:cliente] then 
        compra = session[:compra]
        #Evaluamos si estamos comprando el mismo producto dos veces
        #Aumentamos el coste, pero no duplicamos alimentos
        compra[0] = compra[0]+ params[:comprado][1].to_f
        a=compra[1].index(params[:comprado][0]) 
        if not a then
          compra[1]<< params[:comprado][0]
        end
        session[:compra]= compra
        flash[:notice]= "#{params[:comprado][0]} incluido en la cesta"
      else
        flash[:notice]= "Para efectuar una compra tienes que hacer login antes"       
      end      
      redirect_to productos_path
    end
  end
  def new
    # default: render 'new' template
    # solo disponible para modo encargado
  end
  def create
    @producto = Producto.create!(params[:producto])
    flash[:notice] = "#{@producto.nombre} creado."
    redirect_to producto_path(@producto)
    # solo disponible para modo encargado
  end
  def edit
    @producto = Producto.find_by_id(params[:id])
    # solo disponible para modo encargado
  end
  def update
    @producto = Producto.find_by_id(params[:id])
    @producto.update_attributes!(params[:producto])
    flash[:notice] = "#{@producto.nombre} Acualizado."
    redirect_to producto_path(@producto)
    # solo disponible para modo encargado
  end
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy
    flash[:notice] = "#{@producto.nombre} eliminado."
    redirect_to productos_path
    # solo disponible para modo encargado
  end
end

app/controllers/recetas_controller.rb
class RecetasController < ApplicationController
  def show
    @receta = Receta.find_by_id(params[:id])
    if not @receta then
      flash[:warning]= 'Receta no encontrada'
      redirect_to recetas_path
    end
  end
  def index
    @recetas = Receta.all
  end
  def new
    @productos= Producto.all
    # solo disponible para mordo cliente
  end
  def create
    @receta = Receta.create!(params[:receta])
    @productos =params[:producto]
    @productos.map do |producto|
  	  if producto[1] =='1' then
  		  @producto =Producto.find_by_nombre(producto[0])
  		  @receta.productos << @producto
  	  end
  	end
    @receta.save
    flash[:notice] = "#{@receta.titulo} creada."
    redirect_to receta_path(@receta)
    # solo disponible para modo cliente
  end
  #def edit
    #@receta = Receta.find params[:id]
    # A lo mejor no deberiamos implementar este metodo! o solo para el cliente que la crea
  #end
  #def update
    #@receta = Receta.find params[:id]
    #@receta.update_attributes!(params[:prodcuto])
    #flash[:notice] = "#{@receta.titulo} Acualizada."
    #redirect_to receta_path(@receta)
    # A lo mejor no deberiamos implementar este metodo! o solo para el cliente que la crea
  #end
  def destroy
    @receta = Receta.find(params[:id])
    @receta.destroy
    flash[:notice] = "#{@receta.titulo} eliminada."
    redirect_to recetas_path
    # solo disponible para modo cliente (el q la crea)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clientes/edit.html.haml
%h1 Actualizar información

= form_tag cliente_path(@cliente), :method => :put do

  = label :cliente, :nombre, 'Nombre'
  = text_field :cliente, 'nombre'
  
  = label :cliente, :direccion, 'Dirección'
  = text_field :cliente, 'direccion'  
  
  = label :cliente, :nif, 'NIF'
  = text_field :cliente, 'nif'
  
  = label :cliente, :n_cuenta, 'Número de cuenta'
  = text_field :cliente, 'n_cuenta'  
  
  = submit_tag 'Actualizar'
    
= form_tag cliente_path(@cliente), :method => :get do
  = submit_tag 'Cancelar'

app/views/clientes/login.html.haml
%h1 Entrar

= form_tag clientes_entrar_path do

  = label :cliente, :nif, 'NIF'
  = text_field :cliente, :nif
  
  = label :cliente, :pass, 'Contraseña'
  = password_field :cliente, 'pass'  
  
  = submit_tag 'Entrar'
    
= form_tag homepage_index_path, :method => :get do
  = submit_tag 'Cancelar'

app/views/clientes/new.html.haml
%h1 Registrarse

= form_tag clientes_path do

  = label :clientes, :nombre, 'Nombre'
  = text_field :clientes, 'nombre'
  
  = label :clientes, :direccion, 'Dirección'
  = text_field :clientes, 'direccion'  
  
  = label :clientes, :nif, 'NIF'
  = text_field :clientes, 'nif'
  
  = label :clientes, :n_cuenta, 'Número de cuenta'
  = text_field :clientes, 'n_cuenta'  
  
  = label :clientes, :password, 'Contraseña'
  = password_field :clientes, 'password'  
  
  = label :clientes, :password, 'Repita contraseña'
  = password_field :clientes, 'password'    
  
  = submit_tag 'Registrarse'
    
= form_tag homepage_index_path, :method => :get do
  = submit_tag 'Cancelar'

app/views/clientes/show.html.haml
%h1 #{@cliente.nombre}

%ul#details
  %li
    NIF
    = @cliente.nif
  %li
    Número de Cuenta:
    = @cliente.n_cuenta
  %li
    Dirección:
    = @cliente.direccion
    
=link_to "editar mis datos", edit_cliente_path(@cliente)

%h2 Compra Actual
%ul#details
  %li 
    Total:
    =@compra[0]
  - if @compra[0] != 0
    %li
      Productos:
      =@compra[1]
= button_to "Efectuar compra", clientes_comprar_path, :method => :get
= button_to 'Cancelar compra', clientes_cancelar_path, :method => :get
= button_to "Seguir comprando", productos_path, :method => :get

app/views/homepage/index.html.haml
= image_tag("logo.png")
%links
  = link_to 'Registrarse', new_cliente_path,:class => "homepage_link"
  = link_to 'Entrar', login_path,:class => "homepage_link"
  = link_to 'Productos', productos_path,:class => "homepage_link"
  = link_to 'Recetas', recetas_path,:class => "homepage_link"

app/views/layouts/application.html.haml
<!DOCTYPE html>

%TITULO= link_to "ISIMarket", homepage_index_path

%html
  %head
    %title ISIMarket
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 
  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    
    = yield

%BARRA 
- if session[:cliente]
  %toolbar
    = link_to "#{session[:cliente].nombre}", cliente_path(session[:cliente]), :div => "bar", :class => "barra"  
    %ins.barra Compra:    
    %ins.barra= session[:compra][0]
    = link_to 'Nueva receta', new_receta_path, :div => "bar", :class => "barra"
    = link_to 'Salir', logout_path, :div => "bar", :class => "barra"

app/views/productos/_producto.html.haml
%p
    Stock:
    = @producto.stock

%p
    Descripcion:
    = @producto.descripcion

=link_to 'Cerrar', '', {:id => 'closeLink'}

app/views/productos/edit.html.haml
%h1 Editar Producto

= form_tag producto_path(@producto), :method => :put do
  = label :producto, :nombre, 'Nombre del articulo'
  = text_field :producto, 'nombre'

  = label :producto, :categoria, 'Categoria'
  = select :producto, :categoria, ['verdura','carne','legumbre','lacteo','bebida', 'otro']

  = label :producto, :precio_venta, 'Precio de venta'
  = number_field :producto, 'precio_venta', :min => 0.01, :step => 0.01
  
  = label :producto, :precio_compra, 'Precio de compra'
  = number_field :producto, 'precio_compra',:min => 0.01, :step => 0.01
    
  = label :producto, :stock, 'Stock'
  = number_field :producto, 'stock', :min => 0
  
  = label :producto, :descripcion, 'Descripción'
  = text_area :producto, 'descripcion'

  = submit_tag 'Actualizar Información'
= form_tag producto_path(@producto), :method => :get do
  = submit_tag 'Cancelar'
  

app/views/productos/index.html.haml
%h2 Productos

= form_tag productos_path, :method => :get, :id => 'categorias_form' do
  - @all_categorias.each do |categoria|
    = categoria
    = check_box_tag "categorias[#{categoria}]", 1, @selected_categorias.include?(categoria), :id => "categorias_#{categoria}"
  = submit_tag 'Refresh', :id => 'categorias_submit'
%table#productos
  %thead
    %tr
      %th Producto
      %th Categoria
      %th Precio
      %th 
      %th 
  %tbody
    - @productos.each do |producto|
      %tr
        %td= link_to "#{producto.nombre}",producto_path(producto), :class => 'pop'
        %td= producto.categoria
        %td= producto.precio_venta
        %td= link_to "Recetas", recetas_path
        %td= link_to "Comprar #{producto.nombre}", productos_path(:comprado => ["#{producto.nombre}", producto.precio_venta])

-# hay que mejorarlo con javascript (para el link del nombre del producto a la pagina de show) y el css

app/views/productos/new.html.haml
%h1 Crear Producto

= form_tag productos_path do

  = label :producto, :nombre, 'Nombre del articulo'
  = text_field :producto, 'nombre'

  = label :producto, :categoria, 'Categoria'
  = select :producto, :categoria, ['verdura','carne','legumbre','lacteo','bebida', 'otro']

  = label :producto, :precio_venta, 'Precio de venta'
  = number_field :producto, 'precio_venta', :min => 0.1, :step => 0.1
  
  = label :producto, :precio_compra, 'Precio de compra'
  = number_field :producto, 'precio_compra',:min => 0.1, :step => 0.1
    
  = label :producto, :stock, 'Stock'
  = number_field :producto, 'stock', :min => 0
  
  = label :producto, :descripcion, 'Descripción'
  = text_area :producto, 'descripcion'

  = submit_tag 'Nuevo Producto'
= form_tag productos_path, :method => :get do
  = submit_tag 'Cancelar'

app/views/productos/show.html.haml
%h2 #{@producto.nombre}

%ul#details
  %li
    Precio de venta:
    = @producto.precio_venta
  %li
    Stock:
    = @producto.stock

%h3 Description:

%p#description= @producto.descripcion

%h3 Recetas:
-@receta.map do |receta|
  -receta.productos.map do |producto|
    -if producto.nombre == @producto.nombre then
      =link_to "#{receta.titulo}",receta_path(receta)
      
=link_to 'Volver a Productos', productos_path

app/views/recetas/index.html.haml
%h2 Recetas

%table#recetas
  %tbody
    - @recetas.each do |receta|
      %tr
        %td= link_to "#{receta.titulo}" , receta_path(receta) 
        %td= receta.preparacion
        %td= receta.puntuacion

app/views/recetas/new.html.haml
%h1 Crear Receta

= form_tag recetas_path do

  = label :receta, :titulo, 'Titulo de la Receta'
  = text_field :receta, 'titulo'

  = label :receta, :preparacion, 'Preparación'
  = text_area :receta, 'preparacion'
  
  = label :receta, :puntuacion, 'Puntuación'
  = select :receta , 'puntuacion', [5,4,3,2,1]
  
  = label :producto , :nombre, 'Productos asociados'
  - @productos.map do |producto|
    = producto.nombre
    = check_box :producto, producto.nombre

  = submit_tag 'Nueva Receta'
= form_tag recetas_path, :method => :get do
  = submit_tag 'Cancelar'

app/views/recetas/show.html.haml
%h2 #{@receta.titulo}

%ul#details
  %li
    Preparación:
    = @receta.preparacion
  %li
    Puntuación:
    = @receta.puntuacion
  %li 
    Productos asociados
	
    - @receta.productos.map do |producto|
      = producto.nombre
= button_to "Seguir comprando", productos_path, :method => :get